### ISSUE TITLE
LaTeX Contents table sometimes incorrect

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1053]
**Describe the bug**
E.g. "Bevinding types" is said to be on page 4, but following the hyperlink ends up on a page with a 6 in the footer (which is the correct page).

**To Reproduce**
1. Generated a report
2. Check the table of contents page numbering

**Expected behavior**
Correct page numbers in footer and table.

**OpenKAT version**
1.8.0.1, not yet reproduced on 1.9rc1

**Comment by praseodym** [comment]
This is likely caused by Keiko not rerunning LaTeX a sufficient number of times (it is hardcoded at two runs in v1.8.0). [v1.9.0rc1](https://github.com/minvws/nl-kat-coordination/releases/tag/v1.9.0rc1) switches to XeLaTeX with [Latexmk](https://mg.readthedocs.io/latexmk.html). Latexmk automatically reruns LaTeX as many times as needed, which should fix this issue.

As a workaround in v1.8.0, you can try adding more LaTeX runs in [keiko.py](https://github.com/minvws/nl-kat-coordination/blob/v1.8.0/keiko/keiko/keiko.py#L129).
