### ISSUE TITLE
KAT creates findings when required scans have not run

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1297]
**Describe the bug**
For some findings (created by bits) there are prerequisite boefjes that need to run. However, even when such boefjes are disabled the findings are created. (E.g. from a logic perspective KAT assumes all information is already known to itself, when that assumption cannot be made.)

**To Reproduce**
1. Add a hostname
2. Wait a few minutes
3. Notice DKIM/DMARC findings (while no scans took place)

**Expected behavior**
Not creating findings if you are not sure all the required scans to make those findings have completed successfully.

**OpenKAT version**
1.8

**Comment by zcrt** [comment]
The same seems to hold for `KAT-NO-CERTIFICATE`, but only after KAT has run a few days / a certain selection of boefjes has become active

**Comment by underdarknl** [comment]
This is by design. While we do not have all the required datapoints, we signal that we dont have al the required datapoints. It is unrelated to the ability or succes of specific boefjes, but rather a signal to the user that "for as far as we can see, this domain does not pass requirements", it also holds true for domains that are in your security-path, but are unscannable due to missing indemnifications.

**Comment by zcrt** [comment]
"for as far as we can see, this domain does not pass requirements" does not hold if KAT did not even look

**Comment by zcrt** [comment]
I think it is not a good design if one chooses to report findings for domains in the security path that are unscannable. The best finding would be: "I am not allowed / I was not able to scan domain X for Y" instead of "domain X is vulnerable for Y (oh by the way, I am actually not so sure because I did not even scan / failed my scan)"
