### ISSUE TITLE
as superuser I cannot see all organizations

### ISSUE THREAD

**Issue by ring-ring-ring** [minvws/nl-kat-coordination#1498]
As superuser on my install I get a 403 on organizations I was not originally part of. During testing I was made superuser, but this change does not lead to access to all organizations. 

![image](https://github.com/minvws/nl-kat-coordination/assets/76487016/45e8a691-a320-4b3e-b847-cdd88b0d6dfb)

**Comment by TwistMeister** [comment]
I reproduced this and found out the member isn't added to the organization when receiving super user rights. Therefor the 404 appears. Not sure how to solve this.

**Comment by Donnype** [comment]
This is even an issue when you have multiple superusers and a new organization has been added. Only the superuser creating the new organization will have an organization member for it, while other superusers don't. They will still see the new organization in the drop-down though since we  show _all_ organizations to superusers here.

Thinking out loud, the three possible routes I see are:
- Cover all paths through which a user can become a superuser to create an organization member for this user afterwards for all organizations, and do the same for the creation of a new organization (loop over all superusers). This does not scale well and requires significant investigation to get right.
- Instantiate an `OrganizationMember` in the `OrganizationView` if the user is a superuser, that always has all rights but does not get saved to the database. This is the least-effort route and means we could remove some of the code creating organization members for superusers. However, this abuses the `OrganizationMember` entity for more involved access management and means we need to intercept any `self.organization_member.save()` calls, such as when you press "Withdraw acceptance of level L4 clearance and responsibility". Or pehaps we do want to save the `OrganizationMembers` in this case and let the database entities have precedence over this default `OrganizationMember` object? Should superusers always be able to revoke their L4 clearance level for instance? Then this is perhaps a good option.
- Decouple the `OrganizationView` and `organization_member` field and create a new proxy object that handles all current access to `self.organization_member`. This object can then decide how to handle superusers and regular users separately. In practice this might look a lot like the second option with a lot more refactoring of the current access patterns to `self.organization_member`.

**Comment by Donnype** [comment]
Actually the second option was faster to implement than to write down, so we can also discuss in this PR: https://github.com/minvws/nl-kat-coordination/pull/1695
