### ISSUE TITLE
Plugin settings in .env

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#150]
Currently users can add plugin settings via the UI to "katalogus_db". It's beneficial if this can be done in the .env aswel. When the settings are present in the .env it is no longer required to also add them in the UI to "katalogus_db". Adding the setting in the UI with a different value **could/should** (tbd) override the .env setting.

**Comment by TwistMeister** [comment]
@underdarknl what's your opinion on overriding the .env setting when a setting is present in katalogus_db?

**Comment by Donnype** [comment]
I am not so sure about this. What about new plugins being added that copy the name of the environment and hence can take a look at your secrets?

**Comment by underdarknl** [comment]
@Darwinkel can you describe the multi-layered setup we have now? including envs, katalogus, defaults from the boefje?

**Comment by Darwinkel** [comment]
It currently works like this:

https://docs.openkat.nl/developer_documentation/boefjes.html#environment-variables

By design, Boefjes do not have access to the host system’s environment variables. If a Boefje requires access to an environment variable (e.g. HTTP_PROXY or USER_AGENT), it should note as such in its boefje.json manifest. The system-wide variables can be set as environment variable to the boefjes runner by prefixing it with BOEFJE_. This is to prevent a Boefje from accessing variables it should not have access to, such as secrets. To illustrate: if BOEFJE_HTTP_PROXY=https://proxy:8080 environment variable is configured, the Boefje can access it as HTTP_PROXY. This feature can also be used to set default values for KAT-alogus settings. For example, configuring the BOEFJE_TOP_PORTS environment variable will set the default value for the TOP_PORTS setting (used by the nmap Boefje). This default value can be overridden by setting any value for TOP_PORTS in the KAT-alogus.

**Comment by dekkers** [comment]
This has been implemented
