### ISSUE TITLE
first admin account creation process issue

### ISSUE THREAD

**Issue by evilprime** [minvws/nl-kat-coordination#16]
good day, i am having some problems creating the first admin account, simply put, i am not getting the 'enable' option but instead i am getting the 'submit' option on the right, which suggest the process of creating the admin account has been done allready ? 

i have no idea how to go forward with this, any suggestions? is there a way to reset the admin account? 

regards, 

Lennart

**Comment by evilprime** [comment]
update; i've tried the defaults in this case admin/admin and that worked, i've interpreted the manual as that i needed to create the admin from the get go with the enable option. which in turn would create the first admin.

**Comment by underdarknl** [comment]
Dear Lennart, I see we have omitted the default admin:admin in the docs. Probably because we are moving to a generated password for the first user, which will be communicated on the terminal.
The default manage tooling of django will always work to regain access to the system if you have sufficient command line rights.
