### ISSUE TITLE
Security.txt (kat_sec_txt) boefje runs on HostnameHTTPURL OOIs

### ISSUE THREAD

**Issue by praseodym** [minvws/nl-kat-coordination#1635]
Security.txt (kat_sec_txt) boefje runs on HostnameHTTPURL OOIs, which means it also runs on every sub-page of a website. Running the boefje on a Website OOIs would be better, but then we would need to run it on a specific IP address too. This is not easy with the current sectxt library.

**Comment by praseodym** [comment]
The sectxt Python library source is published at https://github.com/DigitalTrustCenter/sectxt, PyPI at https://pypi.org/project/sectxt/.

**Comment by noamblitz** [comment]
I propose that we do the retrieval part ourselves and just use this package for parsing. What do you think? Looking at the code, this seems like the route of least resistance.

**Comment by praseodym** [comment]
Sounds good. If it is not too much effort maybe we can do the parsing of the txt file in the normaliser instead?

**Comment by noamblitz** [comment]
Yeah exactly what I thought. I will pick it up as soon as i have time.

**Comment by underdarknl** [comment]
That's exactly how I implemented this initially, however, we need to somehow let the normalizer know which url (or url's) where used and where the secrity.txt file was found.
If we are going to way, maybe we should add the parsed security.txt object as a instance in the graph, and have a BIT check for all the various flags and their validity? Adding the object related to an url object telling us where we located it (either /security.txt of /.well-known/security.txt) would then answer some the validity rules. Downloading the files could be triggered by just adding these two url's to the graph and let the website-analyzer boefje retrieve them.
This however has an open end where one, both or none of these url's returns anything other than a 200 / valid security.txt, which would remain in the graph regardless.

**Comment by noamblitz** [comment]
The problem with the current implementation is following redirects, which is not possible if we force ips.

There are two possible solutions that @underdarknl and I discussed.

### SecurityTXT OOIs on Websites
We can add SecurityTXT OOIs that have three attributes:
- The Website OOI
- The URL of the Security TXT
- Optional => the content (if it redirects, the content in None)
- Optional -> to which SecurityTXT OOI this one redirects

When finding a SecurityTXT OOI that redirects, the last SecurityTXT also has the Website on which it is hosted which all has to be created by the normalizer. 

Parsing can be done by bits.

### SecurityTXT OOIs on URLs
This implementation is basically the same as the one above but now only the URLs are created. This loses the context of on which iP the txt is hosted but makes implementation a bit easier.

In both implementations, the findings of the underlying Findings are copied by bits to other Security TXT OOIs so that they can be reported on.

**Comment by praseodym** [comment]
Shouldn't `HTTPResource` OOIs be sufficient for this purpose?

**Comment by noamblitz** [comment]
Yeah but there will HTTPResources for all URLs, which is gonna cloud the task list

**Comment by underdarknl** [comment]
The second option could  do the following:
A bit produces two `httpresources` for every `website`, one with /security.txt as its url, and one with /.well-known/security.txt
Those url's could then be downloaded by our regular tooling. And a normaliser would then target those plain/text files, check their url and consider them to be valid or invalid urls for security.txt contents.
If the url matches, we can parse the contents and create a related `SecurityTXT` ooi related to the url, and origin website, as @noamblitz pointed out, this will give a lot of noise where the normalizer that tries to look for security.txt files cannot be targetted specifically enough and thus ends up running on other plain/text files too (eg,/ robots.txt).
I do think this route is cleaner, but we'd need to be able to target normalizers based on the input-OOI related to the raw-file for this, which we currently cannot do.

For now, I'd say, lets implement option 1 and to cascade redirecting security.txt's from one domain to another by referencing them and copying over the findings
