### ISSUE TITLE
'Wappalyzer - Software Scan' follows redirects and links software (injustice) to the object on which the scan originally started.

### ISSUE THREAD

**Issue by jordy-kennisnet** [minvws/nl-kat-coordination#1662]
**Describe the bug**
'Wappalyzer - Software Scan' follows redirects and links software (injustice) to the object on which the scan originally runs.

This can also lead to scanning a website where no clearance level has been given!

**To Reproduce**

1. Choose a website that offers a redirect to another website (with different software).
2. Scan this website using Wappalyzer.
3. Download the task files and observe where the redirect takes place.
4. Add the redirected URL as an object and perform a scan on it as well.
5. Observe that the same software is detected on both sites, despite the fact that they differ in reality.

**Expected behavior**
When Wappalyzer follows a redirect, it should lead to a new object (the redirected URL). The discovered software must be linked to this new object, and not to the original object where the scan was initially started.

**OpenKAT version**
- Version: 1.10rc2

**Additional context**
In the task file of Wappalyzer, you can see its followed redirects:
{"urls":{"https://web.site/":{"status":301},"https://redirected.url":{"status":200}}

**Comment by underdarknl** [comment]
Seeing that this issue arises more often due to missing config flags, and since we are also seeing tools that we cannot control to access a specific IP I propose the following:
We implement a safeguard around these tools inside the boefjes runner. This could (optionally) replace the resolv.conf with an empty file for that specific container, and specify the correct hostname and IP combo in the /etc/hosts file as given by our input OOI.
This way a redirect would either run into an unresolveable dns entry, or stay on the same host (which probably has the correct indemnifications present)

**Comment by jordy-kennisnet** [comment]
That would be one part of the solution. Because you also want to have a view of the redirects. In other words, which instance would creates a new object - where the redirect is located? Which can be scanned with the correct clearance level or not?

**Comment by Donnype** [comment]
@underdarknl For this specific instance it was quite easy to detect the redirects and create an intermediate step. I suggested a fix in the linked PR.
