### ISSUE TITLE
KAT redirects to homepage after required re-login

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1736]
**Describe the bug**
Quite often KAT decides to no longer trust the end-user and requires a new login. However, after the login, the user has to find its way through KAT again, instead of being redirected to the page that was actually requested when the new login appeared.

**To Reproduce**
1. Use KAT
2. Wait some time
3. Click another page 
4. Instead of showing the page, be asked to login again
5. Do not end up on the requested 'another page' after successful re-login.

**Expected behavior**
Ending up on the requested page, and maybe also requesting re-logins less often.

**OpenKAT version**
1.10.2

**Comment by underdarknl** [comment]
One of the underlying issues causing this is the backwards manner in which sessions in Django are stored, and how they are not 'updated' when a user makes a subsequent request. 
I do agree that we also need to redirect to the last-used url when prompting for a login.
@dekkers Is there a way to move to Signed cookie session storage, which could avoid the overhead of request based session updates against the database, while still providing the same level of security?

**Comment by dekkers** [comment]
If you want to request re-logins less often you can change this by setting the SESSION_EXPIRE_SECONDS env variable.

The problem with the missing redirect is that we don't provide the next parameter when redirecting to the login page. Should be an easy fix, see also https://docs.djangoproject.com/en/4.2/topics/auth/default/#the-raw-way

The Django documentation about sessions has a warning that using signed cookies for sessions makes replay attacks possible: https://docs.djangoproject.com/en/4.2/topics/http/sessions/#using-cookie-based-sessions. I also don't understand how this would fix anything with regards to the missing next parameter.

**Comment by underdarknl** [comment]
The missing next parameter is obviously not being solved by switching to signed cookies, however if the session gets renewed for every request, (something that the DB sessions dont do due to the costs involved) the pain of being redirected gets lower since you dont get a login prompt as much.
Replay attacks based on stolen cookies can be somewhat mitigated by including the remote ip address in the cookie secret, this will automatically invalidate any cookie being offered from a new ip. (which in itself might cause some users on connections with unstable IP's to see more frequent login screens.)
