### ISSUE TITLE
Boefjes should specify which raw file types it produces instead of OOIs

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#1833]
Currently boefjes don't specify which raw file types it produces. The boefje metadata lists OOIs in the produces field, but those aren't produced directly by the boefje, but by the normalizers. This makes it impossible to link to the normalizers that consume the raw files produced by the boefje on the boefje detail page. 

We should list the raw file types in boefje produces. We might also consider adding a check to make sure that a boefje can only return types that are listed in the metadata.

**Comment by underdarknl** [comment]
Since not all mime-types might be known in advance (some boefjes mirror the mime-type they download from remote sources), we should make it clear this list is non exhaustive.
We can however provide a few extra hints on the boefje detail page where we list all mime-types that Bytes has seen from this Boefje (and provide a filtered page of raw-files per mime-type for the user to click to).
Furthermore the boefje/$name and boefje/$name-$version variants are not expected to be set by the boefje developer, and should be automatically added to the manifest list.
Adding a check would be useful, however we'd then also need to be able to signal the possibility of the list being empty or partial as per the first scenario I described.

**Comment by Donnype** [comment]
Since this change will create a big PR with all the boefje.json changes, I created a follow up ticket for rocky: https://github.com/minvws/nl-kat-coordination/issues/1928

**Comment by Donnype** [comment]
@underdarknl Note that even the webpage_analysis boefje has restrictions for its mime-types due to security reasons. Are we really allowing boefjes to define arbitrary mime-types in the future? Because malicious websites would be able to inject certain behavior if we do, given that some logic depends on the provided mime-types.

**Comment by underdarknl** [comment]
So, two separate 'issues' here. One is displaying which mime-types a boefje could probably make (which we can easily list in the manifest). This is fine, but does not need to be the complete exhaustive list I'd say.

And the other is to make sure the mime-types from boefjes don't poison the openkat install.  This could as far as I can see just be a filter to make sure some 'internal' namespaces like boefje/ and normalizer/ are not allowed. 
For now, the 'allo-wlist' that we used in the downloader code relies on the environment present on the system, which allows admin's to configure the allowed-list themselves.

For discovery purposes we could also supplement the listed mime-types with the data from the actual produced mime-types in Bytes for each Boefje.
