### ISSUE TITLE
ConfigOOI for allowing CSP findings to be set either on the website, hostname or url

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#1951]
**Is your feature request related to a problem? Please describe.**
Currently we bind CSP violations to each URL, some users might not need this granularity and would like them to be bound  ( grouped) at the hostname or website. We should allow this by setting a ConfigOOI on the netwerk,or more specifically hostname and website.

**Describe the solution you'd like**
Create QuestionOOI for network for the base setting.
Create ConfigOOI based on the results of this question
Use ConfigOOI (or more specific ConfigOOI's for the CSP bits)

**Describe alternatives you've considered**
Group all CSP violations together into one in the report stage. This could work but still creates lots of OOI's that a user might not need.

**Comment by noamblitz** [comment]
Factually, I prefer the alternative :). It would look something like:

For this website, we found x pages. Of that, we checked y pages for CSP headers. Z pages have missing or incorrect headers. 

If we make it configurable in a config, we lose the possibility of doing that in a report since the report doesn't know where to look for the findings.

**Comment by underdarknl** [comment]
We decided to go along with @noamblitz 's suggestion. We could introduce a bit that aggregates csp url findings onto the website or hostname
