### ISSUE TITLE
NXDOMAIN keeps findings in KAT

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1963]
**Describe the bug**
Suppose a domain is forgotten and has some vulnerabilities. This domain is correctly identified as such and reported by KAT. The owner of the domain then continues to solve the problems. One easy solution is taking down the domain. However, KAT wil not remove its findings once a domain resolves to NXDOMAIN.

**To Reproduce**
1. Have a domain with findings
2. Take down the domain
3. Notice the findings do not dissappear

**Expected behavior**
No more findings as long as the domain resolves to NXDOMAIN.

**OpenKAT version**
1.12.1

**Comment by underdarknl** [comment]
Are these findings bound directly to the domain, or are the present on objects related to this domain (like a webserver?)
In the later case, those related objects should be cleaned up once the responsible boefjes (dnsrecords) cannot proof their existence anymore.
If findings are directly related to the domain, but are created by boefjes that now don't longer have the ablity to run (due to the webserver being removed), we need to find another way to remove them. Ideally we'd make sure that boefjes only create objects related to their input OOI's, and not somewhere else in the graph to avoid this problem.

**Comment by zcrt** [comment]
In this case we saw `dnsrecord` fetch `NXDOMAIN` multiple days ago, but still there exist findings about invalid certificates ('objects related to the domain') for this domain

**Comment by underdarknl** [comment]
Yup, so that means at some point there where dns-records, and an ip-adres, ip-port and service which where the input for the Tls boefjes. Those plugins then coupled the findings no to the service (which has now probably been deleted), but to the Domain. Since there is now no way to invalidate these results they will never be proven as solved.
We should either make sure objects are not bound 'out of scope' into the graph (like what happened here), or we should make sure that the origin (the input-ooi for the tls tools) of these findings triggers a delete on them regardless of where these findings where added in the graph.
@originalsouth this seems like a good first issue for your discovery of how deletion propagation works in Octopoes, and what Origins are in the model.

**Comment by originalsouth** [comment]
> Since there is now no way to invalidate these results they will never be proven as solved.
Right, this goes directly against the Octopoes' OWA...

**Comment by originalsouth** [comment]
Steps to replicate:
1. Spin up a fresh install add an organization and the like
1. Disable all boefjes and solely turn on the "Wappalizer - Software Scan" boefje
1. Have the following OOIs in place on L2: 
    * Network[`internet`] 
    * Hostname[`mispo.es`]
    * HostnameHTTPURL[`https`, `443`, `/`]
 1. Wait until all tasks finish. There should be new OOIs
     ![image](https://github.com/minvws/nl-kat-coordination/assets/5300799/1aa5d040-70cb-4bf8-8ca1-a5a3c0534c0a)
     and new findings:
     ![image](https://github.com/minvws/nl-kat-coordination/assets/5300799/f13eff4f-c305-43cc-bed2-fa22902ffa2a)
 1. Change your DNS settings to have `mispo.es` point to an `NXDOMAIN` (dnsmasq/pihole are excellent)
 1. Rerun all task and observe no changes in OOIs nor in findings
 1. Repeat first three steps (keeping the NXDOMAIN in place)
 1. Wait until all tasks finish. Note there are no OOIs nor any nontrivial findings
     ![image](https://github.com/minvws/nl-kat-coordination/assets/5300799/c6826e8c-9091-4712-8e8e-55b0999b2869)

**Comment by originalsouth** [comment]
Bit test passes meaning delete events are present there:
https://github.com/minvws/nl-kat-coordination/blob/d6d677b261e2caba9997b3c9a865979d3380210e/octopoes/tests/integration/test_ooi_deletion.py#L188-L257
Next up NXDOMAIN after Findings by Normalized Boefjes.

**Comment by originalsouth** [comment]
https://github.com/minvws/nl-kat-coordination/blob/b4cd1049f17a5bfe6cd114341c51206b7df48ae9/octopoes/octopoes/core/service.py#L579
🤔

**Comment by originalsouth** [comment]
Some examples of this bug known so far:

-
    - Boefjes: Wappalyzer
    - URL ooi: https://mispo.es
    - Add manual NXDOMAIN on mispo.es
    - Yield:
        - Software
        - SoftwareInstances
-
    - Boefjes: DNS Records, Nmap TCP
    - URL ooi: https://mispo.es
    - Add manual NXDOMAIN on mispo.es
    - Yield
        - KAT-OPEN-DATABASE-PORT
        - KAT-OPEN-SYSADMIN-PORT
        - KAT-NO-CERTIFICATE
        - KAT-WEBSERVER-NO-IPV6

**Comment by originalsouth** [comment]
NXDOMAIN objects are currently not transitive w.r.t. redirections (not exactly sure what the desired behavior is there)

**Comment by originalsouth** [comment]
Three options to proceed:
1. If NXDOMAIN attached to Hostname delete childeren (OOIs)
2. If NXDOMAIN delete Hostname ( -- and Garbage collect all childeren) keep Hostname in NXDOMAIN object
3. Make NXDOMAIN a subclass object of Hostname and substitute accordingly

**Comment by originalsouth** [comment]
This issue is partially addressed in #2310

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Having difficultly getting the NXDOMAIN setup to work locally, thus trusting @originalsouth on his testing capabilities for that specific part. 

Have verified that the onboarding works, just like enabling and running additional boefjes and generating reports. There appears to be no impact on this. 

### What doesn't work:
n/a

### Bug or feature?:
n/a

**Comment by originalsouth** [comment]
@underdarknl @dekkers perhaps we can setup an "always NXDOMAIN" DNS server somewhere (--mispoes53--) for testing purposes?

**Comment by dekkers** [comment]
I am not sure what you want... requesting a name that doesn't exist will already always return NXDOMAIN, no need to set up something special for that? I think the issue is that we need to test that a hostname first existed and was seen by KAT that everything does the right thing when the hostname doesn't exist anymore.

**Comment by originalsouth** [comment]
> I am not sure what you want... requesting a name that doesn't exist will already always return NXDOMAIN, no need to set up something special for that? I think the issue is that we need to test that a hostname first existed and was seen by KAT that everything does the right thing when the hostname doesn't exist anymore.

In order to simulate NXDOMAINS for OpenKAT developers, the suggestion is to have a "mock" DNS server that serves an NXDOMAIN for any request. This way we can first generate OOIs with a normal DNS server and then simulate an NXDOMAIN event by having the DNS Records Boefje point to our "mock" DNS server (after a restart).

The way I currently do it, is by running my own DNS server... but that is not a scalable solution.

**Comment by dekkers** [comment]
I discussed this with @originalsouth

The problem is as follows:
- Some normalizers return the input OOI creating self-references that don't get cleaned up.
- The finding type normalizers hydrate the finding type and are supposed to return the input OOI.

The possible solution:
- Fix the normalizers so they don't return the input OOI anymore.
- To make sure that we don't have this problem again in the future, we should have a way to distinguish between normalizers that are supposed to return their input OOI and normalizers that should not. The PR changes the finding type normalizers to return declarations, but that is not correct. They aren't really observation either, so we propose to introduce a new 'hydration' type. Then observations should never return the input OOI, while hydrations will return the input OOI.
- A failure is better than silently ignoring returned OOIs. I think it would be better to give a clear error message and mark the normalizer as failed when a normalizer returns the input OOI instead of silently ignoring the input OOI. This makes it also more clear what is going on if in the future people with less knowledge of KAT write boefjes/normalizers.

**Comment by originalsouth** [comment]
Additionally discussed: allow non-hydrating Boefjes to yield their input object, filters will be applied in [job_handler.py](https://github.com/minvws/nl-kat-coordination/blob/d7d497866c37110a9102330684368d79bc86c3e2/boefjes/boefjes/job_handler.py) as currently implemented. A warning will be added when this occurs.
