### ISSUE TITLE
Build CI/CD for building versioned boefje image containers

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#2443]
**Is your feature request related to a problem? Please describe.**
Currently our boefjes are mostly locally stored folders with python code. This needs to be transformed into a Container or archive file based system where each Boefje is self-contained with a well defined entrypoint. These artifacts should be distributable as an archive and a oci-image and contain al needed requirements for the internals of this boefje to function.

**Describe the solution you'd like**

* Describe the requirements per boefje in their own local requirements file.
* Create a build script for each boefje (or a general one if possible)
* Build ci/cd to create versioned artifacts (archive + ico-image) of released boefjes. possibly build for various architectures.
* Setup distribution channel for artifacts
* Connect katalogus to distribution channel
* Have boefje runner collect required artifact (based on local arch, runner type) from distribution channel.

**Comment by Donnype** [comment]
Related:
- https://github.com/minvws/nl-kat-coordination/issues/1628
- https://github.com/minvws/nl-kat-coordination/pull/1620/files

**Comment by Donnype** [comment]
Also in the future it would be great if we could provide easy tooling to build the images outside of kat, but the current scripts at least depend on some imports outside of its scope

**Comment by dekkers** [comment]
### Building images

I don't think we can build every boefje that currently already uses an existing container image using a single builder Dockerfile. So we would need some logic to use a Dockerfile in the boefje directory if it exists and fallback to using the general builder Dockerfile if it doesn't. But maybe it easier to just put a Dockerfile in the boefje directory even if that would cause a bit of duplication.

I think it would be good to not increase the scope too much and tag the boefjes container the same way we do the current containers, so with the OpenKAT version when we add a git tag. This also leaves a bit of room to change the boefjes HTTP API, because we haven't really used it yet and it would be nice to be able to make changes it if necessary.

I think it shouldn't be a problem to just build all boefje images with a single build command in a development setup from source. It takes a bit of time the first time, but after that it would just use the default docker image caching. Those images will then be available in the local docker registry for KAT to use. So I don't think it is necessary to have logic to decide to pull images or build them.

For github actions I think we can use the path filter that used is in the Debian action to only build images when there are changes to the boefje in a PR. I think for releases and maybe also main we always want to build all the images, because you want to make sure that you have the latest base image / security updates.

One aspect that is not mentioned yet is that we need some shared code to do the communication with the boefjes HTTP API. We either need to directly copy that from the source with a statement in the Dockerfile, use multi-stage builds for this, or create a PyPI package that can be installed.

### Finding images

I think discoverability / creating a repository is another discussion we should probably do in another issue. But with regards to the boefje definition and picture, I think that should be included in the container image, either as a file in one of the layers or added as OCI image metadata.

**Comment by Donnype** [comment]
@dekkers True about the boefjes that use containers and agreed on the approach for the fallbacks. I think 60% could use a generic `base.Dockerfile` and the others either use some duplication or we juggle with multistage builds.

I also think that the versioning in tags is a discussion to have later. Wanted to at least point out all the considerations to take into account.

Building all images with one command will cover a lot of cases, but I do see scenario's where perhaps I clean up some old images and suddenly see obscure failures in my install because I miss the images. Wouldn't we save some potential future headaches if we try to build a resource if possible? Perhaps in practice most devs spam `make kat` but I still mostly talk through `docker compose` itself.

The last part indeed I soon realized starting to experiment with this. It would be nice if we could have some generic tooling around this that works with multiple base images and does not require (a lot of) dependencies to bake those image into openkat-compatible-boefjes. In the MVP I just built I combine a bash `boefje_entrypoint.sh` that curls to the boefje API and calls a python-specific `docker_adapter.py` that calls the run method from the boefjes. Could be improved over time when we learned more about the setup.

### Finding Images

Agreed to discuss this in another issue.

**Comment by Donnype** [comment]
With respect to Boefjes that already use a container, as discussed with @dekkers, the simplest solution would be to extend the existing container and install whatever is necessary (i.e. python, perhaps curl) to call and process the scripts in the same container using the tooling we also have for the python boefjes. This allows us to:

- Move the complexity of tweaking the current boefje images to building working Docker images, which aligns with the current experience in the team
- Iterate over the current APIs quickly in the first phase in a language we're comfortable with, i.e. Python
- Rewrite all the boefjes we're currently supporting

We'd lose some build-time, but that's worth the benefits. The same holds for the fact that we'll be shipping bigger images. To remove this dependency we could consider trying to [bundle](https://pyinstaller.org/en/stable/bootloader-building.html) or compile the Python code to pass to the image, or actually switch to a language such as Go or Rust to compile binaries the images can run directly to turn into a boefje.
