### ISSUE TITLE
PDF Tables flow outside margin

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#2493]
**Describe the bug**
Tables in the vulnerability section of the new reporting module flow outside of the .pdf-margin, which makes them not readable.

**To Reproduce**
1. Have vulnerablities
2. Create aggregate report
3. Look at the pdf

**Expected behavior**
All information visible in the pdf.

**OpenKAT version**
1.14.1

**Comment by underdarknl** [comment]
Dear @zcrt 
Since PDF's are tied to their paper format, what layout options would you prefer? Line-breaks when possible, or some other column count when dealing with tables that might become wide?

We could also possibly move some longer strings out to an apendix to make sure they dont end up growing the tables beyond what is reasonable or expected on paper.

**Comment by zcrt** [comment]
Dear @underdarknl, 
It probably depends, though line-breaks sound reasonable. A configurable font-size may also help, as the current font is quite large, thus requiring more space.

Moving out longer strings may be a good solution for some specific vulnerabilities. Especially, when there are multiple vulnerabilities with the same string, which would otherwise result in a lot repetition. Alternatively, some smart aggregation could be applied there. In addition, it is not uncommon for high-resolution PDF's to require zooming capabilities for large tables, though my assumption would be that that is not yet necessary for the current table.

**Comment by underdarknl** [comment]
* Use human readable variants of asset primary keys.
* Use references if we know a given string is always going to be too long for the table / pagewidth.

**Comment by Rieven** [comment]
![Image](https://github.com/minvws/nl-kat-coordination/assets/30832687/c17f4c21-c9b5-4fe8-95cf-5d19361ddf36)

**Comment by underdarknl** [comment]
Weasprint has some issues in parsing css. Lets discuss moving to a real browser engine instead.

**Comment by madelondohmen** [comment]
We've come to the conclusion that more research needs to be done. 

A few options have been discussed, but no conclusion has been reached:
* Keeping WeasyPrint and making adjustments so that the formatting of the PDF matches the HTML (especially the flexboxes)
* Using browser engine PDFs instead of WeasyPrint. The downside is that that this may not support the report flow in the future (with many and large reports)
