### ISSUE TITLE
API Pagination to use in Django ListView

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#2598]
_Please add one or more of the following labels to your issue:_
`frontend` and `backend`

**Is your feature request related to a problem? Please describe.**

1. The way Django uses pagination is to get a complete list of items and slice them into pages. The max items per page is defined by `paginate_by` in Django ListView. How many pages there are is defined by the count (`len`) of all objects. In Django ListView this is the `object_list` attribute or `get_queryset` which sets the `object_list`. 
2. We made a workaround to introduce lazy loading which return a sliced object where it is needed. The problem about this is that it is not how api request should work. You make a request at the moment you want it and get exactly what you asked for.
3. We do not want to get all listed items and slice them, this will take too much time if we are getting 1000's of objects, instead we want to make a query for each page using the parameters in api `offset` and `limit`. The limit stay fixed while the offset move according the page number you want to access. In Django templates it uses `?page=1` etc...

**Describe the solution you'd like**
Create a new Paginator class (https://github.com/django/django/blob/eff21d8e7a1cb297aedf1c702668b590a1b618f3/django/core/paginator.py#L27) and attach this to a custom ListView(https://ccbv.co.uk/projects/Django/5.0/django.views.generic.list/ListView/). When we need to use a Paginator we subclass this new ListView. We want to keep the same style of Django accessing certain values.

**IMPLEMENTATION**

- Get objects for the first page. Doing this we already can do a count of total objects(for all objects no only page 1), which will be used to calculate how many pages we are going to have, which is the `total objects/limit`. If `total_objects%limit == 0`  then we know that we have equal devision of objects, otherwise we use the value `total_objects%limit` will be the last page. So if we have 14 objects and limit per page is 10. then we can do 14%10 = 4 and 14/10 = 1.4 so we need 2 pages where page 1 has 10 objects and page 2 has 4 objects.
- Each page will have its own query, using page number from queryparameters we can know what page we want. The calculation. The limit will always stay the same, the offset will be calculated by `(page_number*limit) - limit`

**Comment by dekkers** [comment]
We need to implement our own `Paginator` class. There is no need for a custom ListView if we implement the same interface as Django's `Paginator` class. For this we need to at least the following parts:

`__init__` that accepts all the parameters because `MultipleObjectMixin` provides all of them when instantiating the class. It should raise an exception if orphans isn't 0 because we aren't going to support that in our Paginator class.

`page` method should not check if the page number is too large by getting the count first (but we still should do the other checks in `validate_number`) and not implement the Django logic with regards to orphans, but just use `self.object_list[bottom:top]`. That might return an empty list and if that happens we need to handle it the same way as the Paginator class currently does: raise `EmptyPage(self.error_messages["no_results"]` if page number is bigger than 1 or if `allow_empty_first_page` is set to False and the first page is requested. If the page number is 1 but `allow_empty_first_page` is True then we should return the empty list.

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Generated multiple pages of findings, tasks and objects. Clicking through the pagination works as expected. Changing the URL parameter also seems to work. 

### What doesn't work:
n/a

### Bug or feature?:
n/a
