### ISSUE TITLE
Documentation for Octopoes Objects

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#2622]
**Is your feature request related to a problem? Please describe.**
Currently, documentation for environment variables is generated automatically. It would be great to have this kind of documentation also available for the [objects of interest (OOI) in Octopoes](https://github.com/minvws/nl-kat-coordination/tree/main/octopoes/octopoes/models/ooi).

**Describe the solution you'd like**
For example: adding docstrings with examples to the OOI code, which can be shown automatically on docs.openkat.nl.

**Comment by underdarknl** [comment]
I agree. @originalsouth has done some work in 'introspection' surrounding the model. Maybe that would be a good start  to provide 'in-install' observability of the current model.

**Comment by ammar92** [comment]
So I've looked into this a little and there are a few options:
- There's `autodoc-pydantic` which recently had some updates and releases
  - It should integrate nicely with our docs generator
  - It has support for `BaseSetting` classes as well
- Introspect the objects and compile a list of model/field combinations, without documentation
  - Although it doesn't fit the requirement, it would still be nice to have some knowledge about the model namespace rather than nothing at all (a list of model with fields combination or a graph of models and their relationships)
- Documenting fields using `Doc` from `typing_extensions`
  - Although introspecting the models and extracting field documentation would work, it would pollute the codebase with a lot of `Annotated[..., Doc("...")]`

To me it seems straightforward to give `autodoc-pydantic` a try. It would be nice if it works, because it would save a lot of code and could also potentially replace our automated settings docs as well.

**Comment by originalsouth** [comment]
Let us assume this also addresses issue #2273
