### ISSUE TITLE
Saving reports for history page

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#2720]
_This ticket is part of epic #2626_

## Description
All the generated reports need to be saved to XTDB, so they can be retrieved and showed in the history page.

### Design
Design of the history page:
https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/%E2%9C%85-KAT-%7C-Approved-for-implementation?type=design&node-id=1183-3471&mode=design

## To do
- [x] Add reference date, object-count and name to Octopoes ReportData
- [x] Save all the reports to XTDB

**Comment by Donnype** [comment]
One important thing to note: I believe the multi-report assumes the data field of the ReportData objects in Octopoes contains aggregate report data. So if we will re-use this object, we should make sure the multi-reports handles this, either at query-time or run-time. (I do think it would make our live a lot easier if we first clean up the report data.)

**Comment by underdarknl** [comment]
Yes, ideally we should store all 'sub-reports' once generated, there's a few ways to do this, (and with the report-jobs heading toward the scheduler for periodic scheduling),  I think it makes sense to do the following:

* A user wants a report and asks as much in rocky, or a schedule is created.
* Create a Report Job. (report type, settings, timestamp, ooi's)
* Run this job in a report job-handler.
* Save the output of this job to Bytes
* * This should be the Report Json
** Possibly also the PDF
** Possibly also the html, although generating the pdf and html could be done at runtime at a later time and is only a small part of the work.
* Ingest this Raw-file with a report normalizer that creates the report-ooi. This might already be available since we currently also ingest aggregate reports this way when creating the sector reports.

For this to work as expected, we need to specify the (Json)-schemas for the various reports, so they can actually be used and combined into 'bigger' reports.

**Comment by noamblitz** [comment]
### Saving Reports

We are going to save reports in XTDB. In this comment, I would like to propose what the OOIs will look like.

## Generate Report vs Aggregate Report

The first distinction between reports is between aggregated and non-aggregated reports. Because aggregated reports are a way of representing generated reports, we could eventually move that calculation to BITs. That might be somewhere far in the future but to prepare for that I would like to add an `aggregate_of` attribute to the ReportData OOI.

## Other attributes
Apart from the `raw` attribute, I propose adding the following attributes:
- Name, in case people want to name their report
- Report Type
- Template
- Date Generated
- Valid  Time
- Input OOI
- ID, I think we would use a generated UUID as a unique identifier of the OOI

## V1
For V1 we can simply fetch all ReportData OOIs (both aggregated and not) and show them in a table to "re-render" them again.

Please let me know if anyone has suggestions about this implementation.

**Comment by dekkers** [comment]
> These are the advantages of saving the (sub)reports when generating an aggregate:
> 
>     1. Easy of use when wanting to download underlying reports, not having to generate them then

This is a trade-off between storing them precomputed or computing them when needed. If we make the assumption that we can't compute the reports in a fast way, there is still an argument to be made for doing either: 

- Organization A might only be interested in the aggregate report. An underlying report is only rarely used and it is no problem if they have to wait a bit for it to be generated.
- Organization B wants to provide the underlying reports to a third party. Computing them when they are fetched takes too long, so they want to save the precomputed underlying reports.

>     2. Clarity and transparency of how aggregates are generated from (sub)reports

I don't really see how precomputing and storing something would give more clarity and transparency instead of computing it when needed it is needed.

Thinking about this more, there might be another advantage:

3. Storing the individual reports might make it easier to parallelize generating big reports. We can create a task for each individual report type to generate the individual report and then a task to create the aggregate report based on the results of all those other tasks. We would have to store the ouput of the earlier tasks somewhere. I think this is only needed for very big reports however.

While the might be a need for storing precomputed individual reports if we can't make computing them fast enough, I don't think there is always a need for it. Maybe we should make it a report configuration to specify what is saved? So that there are checkboxes to save one or more of the following:

- JSON for each individual reports
- JSON of the aggregrate report
- HTML of the aggregate report
- PDF of the aggregate report

> This greatly increases the size of XTDB, therefore de raw jsons will only be saved in bytes and the OOI will just contain the meta of that data in bytes. This also means that aggregate reports cannot be transformed into BITs (data is not saved in the graph).

I agree with saving it to bytes would be better. Saving it in XTDB would not only mean storing the data in XTDB, but it also means XTDB doesn't waste resources indexing the complete nested JSON.

**Comment by noamblitz** [comment]
> ### Input OOIs
> I think we need to save the details of the report that was created/request by the user. The plan is to be able to specify the objects with a query, I think it would be more efficient to save the query instead of a long list of input OOIs in case of very big reports. The query might still specify a list of OOIs if that is what was requested.
> 

A report always has one input_ooi and one report_type. This is different for aggregate reports. If we store the subreports for aggregates, then the aggregate has one report_type and no input_oois, and every underlying report has one report_type and one input_ooi. We can still store the query for the aggregate report though, which might not be a bad idea.

> ### Templates
> Templates will only change infrequently, so instead of copying the report template into each report object it would be more efficient to create a separate Template OOI and reference that. The aggregate and multi-organisation report templates include other templates.
> 

I like this approach! Good idea. 

> Jinja2 is a lot faster than django templates. It also has a sandbox which would limit any potential injection attack that could happen with storing templates in the database. I think we should switch to jinja2 when we save templates in the database to avoid having to do a breaking switch later on.
> 

I can agree on this but switching to Jinja2 for all reports might take some time. Longer than we anticipated for this ticket. 

> We also need to think about how we want to support includes. Maybe the easiest way is to just have the templateOOI have the name of the template, and if you include another template, it will just lookup the templateOOI by name?
> 

Hmm we could. We need to save those includes in XTDB then too.

> ### Date generated
> Maybe creation datetime would be better? I see the creation datetime as the timestamp the user creates the object/requests the report, and generated datetime the timestamp that OpenKAT computed it. There might be a delay if there are lots of tasks on the queue. We already use a certain valid time, so the exact time OpenKAT has generated it might be less useful and creation timestamp might be more useful.
> 

I did not think of the nuance between starting to generate and finished to generate, but indeed creation time it better. 

> ### Report type
> I think this should be plural, because reports can have multiple types?

See first comment
