### ISSUE TITLE
Add functionality in Octopoes/xtdb to load and dump the whole database

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#2761]
Also see: https://github.com/minvws/nl-kat-coordination/issues/2599

We could implement some script that works like Django's [loaddata/dumpdata](https://docs.djangoproject.com/en/5.0/ref/django-admin/#django-admin-loaddata):

```bash
$ cd octopoes
$ python -m dumpdata > dump.json  # XTDB data including tx_time
$ ...
$ python -m loaddata dump.json  # Seeds XTDB
```

**Comment by originalsouth** [comment]
Why not implement it as a XTDB client call so we can both use a script, or use the router (and eventually Rocky)?

**Comment by Donnype** [comment]
Not sure I understand; Rocky does not have an XTDB client, and do you mean the Octopoes router, i.e. the HTTP API?

**Comment by originalsouth** [comment]
> Not sure I understand; Rocky does not have an XTDB client, and do you mean the Octopoes router, i.e. the HTTP API?

I am aware. Octopoes does and indeed I meant the Octopoes router/Octopoes' HTTP API.
 
Such that we:
1. Can gather the required objects from XTDB via the client (within Octopoes)
1. Can implement such a routine/call in the router (Octopoes' HTTP API)

So that we eventually: 
* Have a script that can load/save--import/export objects to/from Octopoes
* Have a smooth UI through for the latter (so an end user can easily load/save--import/export object to/from Octopoes)

**Comment by originalsouth** [comment]
1. Implement in xtdb-cli.py via #2866
    - Possibly add msgpack/bson/gz/lz4/zstd support
1. Add templates to Octopoes IO calls so it becomes more "model based"... 
    - Possibly add msgpack/bson/gz/lz4/zstd support
1. Aggregate towards Rocky et al.
    - Possibly add msgpack/bson/gz/lz4/zstd support
