### ISSUE TITLE
Investigate possibility of `/pop` endpoint returning jobs of the same type

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#2811]
> Further steps investigate possibility of `/pop` endpoint returning jobs of the same type 

 _Originally posted by @jpbruinsslot in [#2613](https://github.com/minvws/nl-kat-coordination/issues/2613#issuecomment-2022199473)_

**Comment by jpbruinsslot** [comment]
- Add queryparam to `pop` api endpoint to return multiple items instead of one
- Response model returning a list instead of one. Default behaviour is to return list with one item

**Comment by underdarknl** [comment]
To summarize:

We want the job runner to receive all similar jobs from the scheduler of type X if type X is the job the scheduler would return if asked for a single job, and if job X's boefje has a flag that tells us batched jobs are in order.
This would allow the job runner to receive a ilst of these jobs, combine them (if the job runner can handle that, else just execute them one by one), and send the newly combined job to the boefje for processing. The boefje would then do its internal optimized magic to be more efficient when dealing with large amounts of input-objects.

This optimization would allow for example the RPKI boefje to ingest all IP-addresses at the same time, parsing and updating its RPKI-input data only once, sort the given IP's, and iterate over all the ipranges listed in the rpki-source instead of over the ip-addresses for each original job, while still creating a correct answer for each ipaddresses based on its iprange.
