### ISSUE TITLE
Add new organisation

### ISSUE THREAD

**Issue by trideeindhoven** [minvws/nl-kat-coordination#31]
I would like to add another organisation to KAT by going to:
localhost:8000/organizations/

I can see my dev organisation there and i can add and remove members from this organisation, but i dont see an option to add another organisation. How can i do that?

 - OS: Debian 11.4
 - Browser Firefox 91.11.0
 - latest OpenKat from github

**Comment by underdarknl** [comment]
dear @trideeindhoven you are correct.
To add a new organisation, one also needs to create the underlying XTDB database. Because we have not automated that part, we have removed the 'easy buttons' to add the other records in KAT for now, but it is obviously still possible.
@dekkers could you help with a shell script to setup an extra XTDB instance? Once that is present the organisation record can be made from the Django admin panel, be sure to use the same Short-code for the XTDB path and in the KAT record.

**Comment by underdarknl** [comment]
Progress update, we have a working XTDB image that allows for multiple 'nodes' to be present in the same database. These nodes will map to organizations in KAT.
We are now working on getting the needed tooling in Rocky (the user interface), and make sure that we hit the correct creation and deletion api's for the other services when we add or remove an organization.

**Comment by underdarknl** [comment]
Fixed in 1.5
