### ISSUE TITLE
Question OOIs are not properly handled in backend

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3192]
**Describe the bug**
Data that is impacted by the Question OOIs are not properly handled by the backend.

The logs do not contain any error messages relating to this bug. 

**To Reproduce**

1. Go through the onboarding flow.
2. Add HTTPHeader object for mispo.es with as key: `Content-Security-Policy` and as value `default-src https://githubpages.com`.
3. Enable Nmap TCP + Webpage analysis and give mispo.es Hostname L2 clearance.
4. Go to the `Question` object for `disallowed-csp-hostnames`. Click the submit button. 
6. Wait until all tasks are done. 
7. Check on the object page the page for the CSP header with a reference to the github pages. 
8. Observe that no findings are created for this object.  

**Expected behavior**
Output from the Question object should be parsed into findings. 

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/9821756/22f83a84-e935-41f7-b3bf-2d20833b16ef)

![image](https://github.com/minvws/nl-kat-coordination/assets/9821756/d97e4252-54b7-4f36-8577-2a40687d19c3)

**OpenKAT version**
main 

**Additional context**
This bug was identified while doing the QA for #3165. This PR hasn't been properly checked and should thus be picked up at a later point in time.

**Comment by underdarknl** [comment]
My guess is that adding a Config Object does not trigger a rerun on the associated Bits that consume that config.

**Comment by originalsouth** [comment]
To minimally reproduce:
* Enable Boefjes: 
        - NMAP TCP
        - DNS Records (A)
        - WebPage Analysis
* Answer "Question|/bit/disallowed-csp-hostnames|internet" with `github.com,google.com,asfsdgswrgew223424.com`
* Add URL: `https://mispo.es` and give it clearance on L2
* Wait until "Finding: KAT-DISALLOWED-DOMAIN-IN-CSP @ Content-Security-Policy @ http://mispo.es:80/ @ 134.209.85.72 contains asfsdgswrgew223424.com" appears
* Answer "Question|/bit/disallowed-csp-hostnames|internet" with `github.com,google.com` (removing asfsdgswrgew223424.com)
* Note that "Finding: KAT-DISALLOWED-DOMAIN-IN-CSP @ Content-Security-Policy @ http://mispo.es:80/ @ 134.209.85.72 contains asfsdgswrgew223424.com" does _not_ disappear until a "Rerun all bits" is initiated

The latter can be repeated by adding or removing asfsdgswrgew223424.com, rerunning all the bits and observing the mentioned finding respectively.

The actual bug is thus that the mentioned Finding (produced by disallowed_csp_hostnames bit) is not updated by changing the answer to the question.

**Comment by originalsouth** [comment]
Other workaround would be to treat config's and parameters on equal footing -- which raises the "question", why are configs special (with regard to parameters)?
