### ISSUE TITLE
Allow enable/disabled normalizers per organization

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#323]
The katalogus should expose api's for enabling and disabling normalizers for each organization.
This api can then be used to render the katalogus in rocky, and allow users to configure their KAT-instance.

**Comment by underdarknl** [comment]
@Lisser do we need to do something special when disabling a normalizer? Eg, remove all known OOI's that where created using this? Or do we keep things as is, just like when you disable a Boefje in the current situation? This could mean various OOI's will never be removed / updaten anymore. But the same is true for disabling a boefje.

**Comment by Lisser** [comment]
In Octopoes v3, events should be sent to Octopoes so that it can respond to these changes.

Regarding the desired behaviour upon such events, I am not sure. 

What sounds most logical to me, is to remove any results from the current valid-time, coming from a boefje/normalizer, when such a plugin is disabled...

**Comment by underdarknl** [comment]
related to the recent question:
https://github.com/minvws/nl-kat-coordination/issues/230
