### ISSUE TITLE
Improve env/settings/allowlist configuration logic for the boefjes

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#3356]
TODO:
- [x] Make adhering to the schema to be enabled optional in the API
- [x] Use the schema keys instead of environment keys in the runner, override with katalogus entries instead of vice versa
- [x] Phase out environment keys in the `boefje.json` files in favor of the `schema.json` keys, as these are now redundant.
~- [ ] Update schema/api checks in Rocky if needed~

part of https://github.com/minvws/nl-kat-coordination/issues/3052.

**Comment by underdarknl** [comment]
> Make adhering to the schema to be enabled optional in the API

N.b. this is needed in situations where the runner injects global env-vars, and as such the fields in the boefje config themselves can be left empty. Instead of bringing the global vars to the validator, we have two options:
Ignore the validator, or ignore the required fields. We opted for the first for now
