### ISSUE TITLE
Creating new boefjes

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3367]
### Detailed description
This is the implementation of #3318 

### Feature benefit/User story
As a KAT user, I want to be able to create and add my own boefjes, so I can make customize plugins that fit my needs.

### Specifications
The implementation should include…

- [x] "Add boefje" button on Boefjes-page
- [x] "Boefje setup" page with a form
- [x] Update "Boefje details" page
- [x] Set permission to admin only

### Screenshots

_Include screenshots of the proposed design changes here._

### Figma link
[Approved | Boefjes | Create a Boefje](https://www.figma.com/design/D48Pf9lLpxET1jp0Wsjzw5/%E2%9C%85-KAT-%7C-Approved-%7C-Boefjes?node-id=2301-6042&t=OkC1Ba5bbLcxjHzG-1)
[For Review, not final!](https://www.figma.com/design/wTD4hfTbZMp0o2G6VmUepU/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Boefjes?node-id=2472-25863&t=CApMFcgwxwOXg6sw-1
)
## Implementation

_This part should only be filled in by the developers._

### Possible solution

_Outline your proposed solution for implementing the feature. You can include any specific ideas, designs, or functionalities here._

### Alternatives considered

_Describe any alternative approaches or solutions you've considered, and why you believe the proposed solution is superior._

**Comment by stephanie0x00** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [ ] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [x] Objects and Findings are created properly
  - [x] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [ ] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
Onboarding seems to work, the UI does have a few unexpected changes. See the screenshots below. 

### What doesn't work:
When adding a boefje the task runs, but it seems to always fail. I did the onboarding with mispo.es.  I used the following settings: [add-boefje-katalogus.tar.gz](https://github.com/user-attachments/files/16796672/add-boefje-katalogus.tar.gz)
- Container image: ghcr.io/minvws/openkat/nmap
- JSON schema + arguments remain unchanged
- Input object type: tried with IPaddress and IPv4 address
- output mimetype: boefje/nmap
- Clearance L1

Other points: 
- I think it will be useful to have helper functionalities for all data fields on the 'Add boefje' form. It can be very daunting to add your own boefje and having the helper functionality can be very comforting. 
- The documentation button at the top "you can check out the documentation" doesnt point to actual documentation. 
- JSON schema Helper functionality should point to an example schema.json file in the repository. This will help the user to quickly have an example ready. 
- Input object type: I think a little more explanation would be nice specifying what it means that "Select the object type that your boefje consumes". Either with a few extra lines and/or a link to documentation where this is described. Just like is done for the 'Output mime-types'.
- Output mimetypes should be with a space for mime types. 


### Bug or feature?:
- There is no check if a boefje with a similar name already exists. Is this intended behaviour? Otherwise it can be very confusing.
- There is currently no way to edit your boefje? Thus if you made a mistake, you cannot edit or delete it after you created it? 


### Screenshots onboarding UI




Onboarding flow UI looks different from main. Is this intentional? I do not see this change listed. 
![image](https://github.com/user-attachments/assets/61826c94-f82a-4924-8e3a-d9136a37c67e)

![image](https://github.com/user-attachments/assets/1466f0fa-1f4f-4084-bd96-36817234d9b8)

**Comment by madelondohmen** [comment]
> ### What doesn't work:
> 
> When adding a boefje the task runs, but it seems to always fail. I did the onboarding with mispo.es. I used the following settings: [add-boefje-katalogus.tar.gz](https://github.com/user-attachments/files/16796672/add-boefje-katalogus.tar.gz)

This will be fixed by @Donnype 


> Other points:
> 
>     * I think it will be useful to have helper functionalities for all data fields on the 'Add boefje' form. It can be very daunting to add your own boefje and having the helper functionality can be very comforting.

I've updated the helper texts and added it for the "Description"-input. I did not add it to "Name", since this is too obvious and not to the "Container image"-input and the "Arguments"-input, since those two already have a small description/example above the input.

>     * The documentation button at the top "you can check out the documentation" doesnt point to actual documentation.

Should be fixed now. The current documentation is only about creating a Boefje in the backend. We still have to update this documentation and add the created UI, but this will be done in a new ticket #3437


>     * JSON schema Helper functionality should point to an example schema.json file in the repository. This will help the user to quickly have an example ready.

Fixed

>     * Input object type: I think a little more explanation would be nice specifying what it means that "Select the object type that your boefje consumes". Either with a few extra lines and/or a link to documentation where this is described. Just like is done for the 'Output mime-types'.

Fixed

>     * Output mimetypes should be with a space for mime types.

Fixed 


> ### Bug or feature?:
> 
>     * There is no check if a boefje with a similar name already exists. Is this intended behaviour? Otherwise it can be very confusing.

This is okay for now. We might fix this in the future.

>     * There is currently no way to edit your boefje? Thus if you made a mistake, you cannot edit or delete it after you created it?

This is correct. For now it's not possible. This is another ticket.
 

> Onboarding flow UI looks different from main. Is this intentional? 

Yes, this is intentional. The lay-out of the form has changed a bit.

**Comment by stephanie0x00** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [x] Objects and Findings are created properly
  - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [x] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
Can create a boefje, enable and disable it and it runs and is picked up by the normalizer (tried with a nmap variant). Other boefjes still run and all create findings. Seems to work as expected now. 

### What doesn't work:
n/a

### Bug or feature?:
The newly created boefje still shows the uuid in the tasks overview on the normalizer page. This will be picked up in a different PR as it is small, such that we can merge this one.
