### ISSUE TITLE
Design a flow for setting/changing the clearance level on objects

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#342]
Setting/editing the Clearance Level (CL) of an OOI is cumbersome and can have severe consequences. To guide the user in this process, while making it easier, we want to think about the user flow on this.

Note: It could have some technical limitations that need to be addressed in Octo3.

**Comment by underdarknl** [comment]
Is this still relevant?

**Comment by HeleenSG** [comment]
**Current issues:** 

- When adding an object manually the clearance level can't currently be set during initial setup. This is confusing. It can't be the same form (step) because octopoes needs an object to be saved before it can determine its inherited clearance level. A follow up step might solve this?
- Editing a clearance level is currently within a tab. But not on the object edit page which is confusing. Adding the option to the edit page as well might solve this.
![Image](https://github.com/minvws/nl-kat-coordination/assets/11405133/f09b4b49-91c5-4a6e-bd1c-84895d87b6b4)
- Changing clearance levels will redirect the users to the account page. This is disorientating because it removes the user from their current work flow. It often doesn't help solve the issue as the levels can't be changed unless the user still has a higher clearance level to accept which they we're granted by their admin. But even when that's the case it would be better to keep the user in the same flow and offer the option to change it there.

**Comment by HeleenSG** [comment]
Created separate work tickets based on these findings. 

- https://github.com/minvws/nl-kat-coordination/issues/3045
- https://github.com/minvws/nl-kat-coordination/issues/3046
- https://github.com/minvws/nl-kat-coordination/issues/3047
