### ISSUE TITLE
False Critical Kennisnet Finding: KAT-CERTIFICATE-EXPIRED @ Let's Encrypt 

### ISSUE THREAD

**Issue by paulvandenbraken** [minvws/nl-kat-coordination#3432]
**Bug-description**
The findings-report of Kennisnet reports: KAT-CERTIFICATE-EXPIRED @ Let's Encrypt(ID), an exiped certificate for tggr.edurep.nl. However, this domain has been cancelled so the critical finding is irrelevant.

**Reproduction**
Look for Critical findings in crisis room and investigate details. 

**Expected behavior**
If a certificate is no longer offered/hosted on a web service, this report should not appear. In other words: the host must be offline, or the certificate is no longer offered. If you take such a situation into account, it will possibly apply to more use cases.
![Fig-1](https://github.com/user-attachments/assets/44daf85d-a32d-46d2-abbf-9e178257b314)
![Fig-2](https://github.com/user-attachments/assets/52c0fb43-1db5-4d38-ae2c-0519726a3693)

**Comment by underdarknl** [comment]
I would expect Kat to clean up the domain, and related certs if you delete the hostname as one of your assets. 
I would also Expect Kat to do the same once we see an NXDomain for the hostname, and raise a critical on that.

**Comment by noamblitz** [comment]
I am trying to reproduce this. Few questions:
- what is the clearance level of the Website object: Website|internet|145.57.36.234|tcp|443|https|internet|tggr.edurep.nl
- what happens if we manually trigger the certificate boefje on that website (should result in the removal of the cert)
- what jobs are listed in the Inferred by and Observed by tables of the website, I expect there to be something like this:
<img width="2010" alt="image" src="https://github.com/user-attachments/assets/388e6758-5c00-409c-b9e5-d98e5edf8b66">
Now, if we click on the ResolvedHostname, and then look at the Inferred by table again, I expect something like this:
<img width="1775" alt="image" src="https://github.com/user-attachments/assets/79a8f4f7-de45-414d-a692-1aa7a4d96a36">
If we click on the DNSRecord I expect something like this in the Observed by table:
<img width="1993" alt="image" src="https://github.com/user-attachments/assets/9d56cfb8-8af4-4710-95d7-6aa4d7f96e12">
Is the Hostname tggr.edurep.nl listed as input OOI here? Could you screenshot the Observed by and the Inferred by tables of this Hostname OOI?

**Comment by originalsouth** [comment]
Blocked on #3499

**Comment by originalsouth** [comment]
> Blocked on [#3499](https://github.com/minvws/nl-kat-coordination/issues/3499)

To add, the bug is functionally already resolved but there a some small things under the hood that need to be taken care off for other such bugs.

**Comment by originalsouth** [comment]
Fixed for all practical purposes.

**Comment by paulvandenbraken** [comment]
First retesting shows this is resolved, we have closed this issue in our JIRA.
