### ISSUE TITLE
Output Webpage analysis

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3487]
**Describe the bug**
When verifying if #3187 was resolved for the Kennisnet URL we ran into a different issue that might be (also) the cause of their bug not showing any Software Instances. 

When the Webpage Analysis boefje ran on the host it contained the following output in the raw file: 

```
<body>
		<app-root></app-root>
	<script src="runtime.111bb50311687970.js" type="module"></script><script src="polyfills.e66d832bff1c2904.js" type="module"></script><script src="scripts.f00f2801fe22a025.js" defer></script><script src="main.1cdf596b1a93223e.js" type="module"></script></body>
</html>
```

However, when inspecting the HTML of the URL we can see that the software version is shown in the HTML. As shown by the screenshot below (first row): 

![image](https://github.com/user-attachments/assets/638b3f76-f147-4c45-9e5c-41e81ac89f8e)

**To Reproduce**

1. Enable the DNS boefjes, nmap TCP, Webpage analysis and Snyk.io
2. Set L2 clearance on the host. 
3. Wait for it to finish
4. Inspect the raw file for the webpage analysis boefje to observe that the HTML has changed.
5. See error

**Expected behavior**
The output HTML contains the observed data and this is then properly parsed into software version objects. 

**OpenKAT version**
main

**Comment by noamblitz** [comment]
After running the normalizer locally and following what happens, it seems like python-Wappalyzer misses these versions because they are "new" and Wappalyzer is not updated to recognize these newer versions. As long as we keep supporting this archived Wappalyzer project, this will continue to happen more and more. Maybe we should consider finding (an) alternative(s) for python-Wappalyzer. I cant solve this bug at the moment...
