### ISSUE TITLE
Errorlogs - No module named pylibjpeg

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3551]
**Describe the bug**
The following error is flooding the katalogus logs. 

```
katalogus-1  | 2024-09-18 10:36:11 [debug    ] boefjes.plugins.models is not a package
katalogus-1  | 2024-09-18 10:36:11 [debug    ] boefjes.plugins.pdio_subfinder.main is not a package
katalogus-1  | 2024-09-18 10:36:11 [debug    ] boefjes.plugins.pdio_subfinder.normalize is not a package
katalogus-1  | ERROR [pydicom.pixels.utils] No module named 'pylibjpeg'
katalogus-1  | Traceback (most recent call last):
katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/pydicom/pixels/utils.py", line 1274, in _passes_version_check
katalogus-1  |     module = importlib.import_module(package_name, "__version__")
katalogus-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
katalogus-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
katalogus-1  |     return _bootstrap._gcd_import(name[level:], package, level)
katalogus-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
katalogus-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
katalogus-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
katalogus-1  |   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
katalogus-1  | ModuleNotFoundError: No module named 'pylibjpeg'
```

**To Reproduce**

1. make reset on a fresh kat install
2. Open the katalogus logs and scroll down a bit until you see the error. 

**Expected behavior**
No error messages in the logs. 

**OpenKAT version**
main

**Comment by zcrt** [comment]
We did see the same behavior yesterday. This issue is likely related to `katalogus` trying to import all boefjes to see whether or not the boefje is allowed to be listed (if it is immediately throwing errors it isn't). In our case, it seems that the scheduler thinks `katalogus` is unhappy during these tests, which makes the Django frontend `rocky` throwing `SchedulerErrors`

If that is the case, this issue should be automatically solved when all boefjes use the new container structure. 

In this specific case, there seem to be issues with `pydicom` / `pynetdicom` used by the Dicom boefje. A potential workaround in this situation may be moving the ` from pynetdicom import AE` to the `run` function of the boefje. However, the boefje itself should be fixed in the end. We also noticed `pynetdicom` immediatly trying to download some files on import and wonder if that is actually necessary.
