### ISSUE TITLE
Reports - Suggested plugins checkbox not working properly

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3691]
**Describe the bug**
The "Show enabled plugins" checkbox in the Suggested Plugins section of the report flow isn't working properly. 

![image](https://github.com/user-attachments/assets/eb5e8422-6037-42aa-9238-9c9540291be1)

**To Reproduce**

1. Go the plugins page in the Reports flow
2. Click on the" Show enabled plugins" in the Suggested plugins section. 
3. Observe that the enabled plugins aren't showing. 

**Expected behavior**
Toggling the Show enabled plugin checkbox shows and/or hides the enabled suggested plugins.

**OpenKAT version**
main

**Comment by TwistMeister** [comment]
I have looked into this "bug" and found that it works as intended. I've verified this with @stephanie0x00 and see agreed that she overlooked a UI changes after checking the box, which was the expected behaviour.

What remains is a valid question: "is the UI change obvious to the user, as an indication that checking the box resulted into a different set of plugins"? This doesn't seem the case, based on @stephanie0x00 her experience.

I will take this up with @HeleenSG , to think about other UI features/behaviour, to improve the UX.
