### ISSUE TITLE
[Bug] CVEFinding gives incorrect Severity/CVSS 

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#461]
**Describe the bug**
When any CVEFinding is found this is reported by KAT as a critical vulnerability with risk level score 10. This is probably due to a missing entry in [OOI_database_seed.json](https://github.com/minvws/nl-kat-coordination/blob/main/rocky/OOI_database_seed.json). However, the actual (NIST) severity (CVSS) can be quite different.

**To Reproduce**
1. Find a CVE vulnerability with KAT
2. Notice it is reported as critical, regardless of the actual CVSS.

**Expected behavior**
KAT should incorporate the actual properties for a known CVE, such as CVSS. 

**OpenKAT version**
1.6.2

**Additional context**
Related: https://github.com/minvws/nl-kat-coordination/issues/152

**Comment by noamblitz** [comment]
I cant reproduce this. Could you give me the CVE? If I add CVE-2018-14040, the CVSS is shown correctly.

**Comment by noamblitz** [comment]
CVEs are not added in the database seed. Their information is added from NIST when a CVE is found for the first time.

**Comment by underdarknl** [comment]
If the CVE itself does not have a score just yet (due to embargo or some other reason) we opt for giving it a 10, right?
Maybe, the KAT install for @zcrt cannot access the remote knowledge information, and therefor defaults to score 10 for all cves?

**Comment by noamblitz** [comment]
The CVEs that were added do not have a CVSS v2 score and are therefore scored as Critiical by KAT just to be safe

**Comment by zcrt** [comment]
Is there a rationale behind using CVSSv2 instead of CVSSv3?

**Comment by underdarknl** [comment]
Yes, CVSSv3 is a more complex rating system where more `currently unknown` values should be taken into account. Just taking a CVSsv3 at face value from the source would be meaningless. However, since KAT does actually grow to know all those extra metric we can in the future hopefully calculate them in a meaningful way ourselves.

The math can be seen here:
https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator

**Comment by zcrt** [comment]
I do not agree that taking the CVSSv3 would be meaningless. Especially for known vulnerabilities found by boefjes querying external applications, I deem it more meaningful to have the (official) CVSSv3 score for a CVE instead of marking it as `critical` in KAT and pretending the CVSS breakdown is non-existent. By the way, as I understand it, the classification `critical` is [not even part of the CVSSv2 framework](https://nvd.nist.gov/vuln-metrics/cvss). Additionally, [new CVEs will not get a CVSSv2 score](https://nvd.nist.gov/vuln-metrics/cvss/v2-calculator) anymore.

**Comment by tobiasBDO** [comment]
Why did you guys opt for the use of the[ `ares`](https://github.com/barnumbirr/ares) PyPi package which uses https://cve.circl.lu, instead of the[ `nvdlib`](https://nvdlib.com/en/latest/index.html) package which uses the [NIST CVE API](https://services.nvd.nist.gov/rest/json/cves/2.0)? The NIST API provides both CVSS 3.1 and CVSS 2.0 (when available).

**Comment by praseodym** [comment]
ares also looks dead (last commit February 2021, last PyPI release April 2020) compared to nvdlib which has seen a release last month (March 2023).

**Comment by dekkers** [comment]
This has been solved in 1.10. We use the newest CVSS data that is available from NVD. When there is no CVSS data, the severity will be UNKNOWN.
