### ISSUE TITLE
[Bug] Common open ports are not reported as findings

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#543]
**Describe the bug**
Common ports such as 443 do not end up in KATs findings. However, not every service with port 443 open was also intended to have that port reachable by KAT. In a report, as an end-user I want to know all open ports that KAT has found.

**To Reproduce**
1. Scan a website
2. Generate a report
3. There is no finding for a common open port

**Expected behavior**
Report all open ports seen by KAT.

**OpenKAT version**
c799f181cdd4569304925f625affcf9f58092607 (latest)

**Additional context**
https://github.com/minvws/nl-kat-coordination/blob/82d64a588f641ab3551a7c338393235dfd0e4774/octopoes/bits/port_classification/port_classification.py#L35

**Comment by underdarknl** [comment]
There are two ways for this to be done.
The first would be to move the various lists of ports from inside the BIT, to inside the graph, where they can be added/changed by users. The Bit would then look for this ConfigOOI and match ports listed there against the ports seen on an IP. This would also allow more fine-grained control of these settings, as you could bind a ConfigOOI to a Network, but also directly to an IPAddress to make specific changes based on your requirements. Following that would allow you to have more or less findings based on your config.

The second would be to include all ports in the report you are looking at. Since all known ports are present in the Graph, we could just include them in the query that produces the report. This for the moment is a bit too complex, but is something that would become much easier when octopoesV3 becomes available.

**Comment by zcrt** [comment]
I would opt for the second option as I always want to know all ports that are open on all IPs I scan with KAT. Why is it complex at the moment? It is already possible to filter on IPPort on the object page, so adding similar logic to all reports should be enough
