### ISSUE TITLE
Superusers don't have a wildcard to do "everything" sometimes they still need to be part of group "redteam" or "admin"

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#559]
A few examples (but probably not all):
In 1.7.0rc3:
- [ ] A superusers still needs "admin rights" to grant clearance to users
- [ ] A superuser still needs a clearance level to be able to give clearance on objects

In essence the super user should have all permissions, and we should check accordingly, instead of only checking on groups.

**Comment by dekkers** [comment]
I would just change the those checks to always allow superuser for now. It's something that is easy to do and would fix this for people who just want to try out KAT and will be using it as superuser. We can easily backport such a fix to 1.7.

When we have a good design for roles & authorization we can implement this in a cleaner way.

**Comment by praseodym** [comment]
Django already returns `True` for all permission checks (`has_perm`) on superusers, so if we use the same logic in the frontend as well we should be fine.

**Comment by Rieven** [comment]
Keep in mind that in the onboarding flow at account setup stage, when continuing as a single account, the superuser will be added as a redteamer, also having having the set of permissions set on redteamer. This should also be removed from the onboaridng flow.

**Comment by praseodym** [comment]
In my findings, all authorizations are currently already checked based on user permissions (`perms.tools.*`) and not on groups. Because the Django superuser implicitly has all permissions (the `has_perms` check always returns `True`), this should already allow the superuser to do everything.

The superuser does need to have a sufficient level of clearance, but the onboarding process currently assigns L4 clearance to the superuser. I tested this with a clean instance; my previous dev setup's superuser did not have any clearance but I cannot determine why this was the case.

Unless anyone has any other findings, I'd propose we close this issue.

**Comment by TwistMeister** [comment]
It appears @praseodym is right, it indeed seems to work as intended. I think I mistakingly took "not being able to assign clearance to a client" for a bug, but this is intended behaviour, except we don't want the option to show up disabled, we want to have it not show up at al, for this situation. That will be addressed in another issue.
