### ISSUE TITLE
Scheduler crashes when postgres database becomes unavailable

### ISSUE THREAD

**Issue by sigio** [minvws/nl-kat-coordination#588]
When the postgres database used by scheduler becomes temporarily unavailable, for example due to a restart or a temporary network issue, it goes into a state where it no longer functions, and requests for /(lang)/(code)/tasks result in error-pages even after the database has been available again for a long time.

This can be resolved by restarting the scheduler, but this should not be needed, scheduler should retry connections to the database (with exponential backoff) in case of failed connections.

**Comment by jpbruinsslot** [comment]
Able to reproduce with:

1. Go through onboarding, add task
2.

```
$ docker-compose kill postgres; sleep 15; docker-compose up -d postgres
```

Eventually, it will crash during a transaction and will shutdown the scheduler.

---

In the case of the scheduler continues to run, while in the meantime the database connection has been lost. And that the tasks endpoint continues to return error-pages. I wasn't able to reproduces it. I've added [`pool_recycle`](https://docs.sqlalchemy.org/en/13/core/pooling.html#setting-pool-recycle) setting to the connect, this might alleviate this problem.

---

As far as the first issue I can implement a retrying query class in sqlalchemy, so that it will retry failed sqlalchemy queries when a transaction failed.
