### ISSUE TITLE
"make kat" Does not recognize already present postgres server, use that instead of starting new server.

### ISSUE THREAD

**Issue by marco-237** [minvws/nl-kat-coordination#59]
I'm trying to install OpenKAT on Kali Linux.

The build and installation fails when doing a "make kat" in ~/nl-kat-coordination with:

ERROR: for bytes-db  Cannot start service bytes-db: driver failed programming external connectivity on endpoint nl-kat-coordination_bytes-db_1 (3e5401790a7c426ff9b52522a15899fe32d6028a2bec91b361a1f75c866eb5fd): Error starting userland proxy: listen tcp4 127.0.0.1:5433: bind: address already in use

ERROR: for rocky-db  Cannot start service rocky-db: driver failed programming external connectivity on endpoint nl-kat-coordination_rocky-db_1 (78c5bb839aeaf7ee597d8836f9aabea5e16ce383084a21b78a07d1ee3f3fe906): Error starting userland proxy: listen tcp4 127.0.0.1:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.

These ports are already in use by PostgreSQL.

So is it possible to change the ports for bytes-db and rocky-db? I've tried to change portnumbers in the env files and other config files but with no avail.

Regards,
Marco

**Comment by underdarknl** [comment]
Marco

If you already have a postgres server, there would be no reason to start another one. The databases can be co-hosted in the same database server, but we might need to make sure the install script understands this and handles adding the databases to an already present postgres server instead of trying to create a fresh one.
