### ISSUE TITLE
Retrieve findings crashes Rocky when too many findings are present

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#613]

**Comment by underdarknl** [comment]
Specifically, the crisis room and findings page crash because Octopoes returns 0 bytes. In turn Rocky crashes because it tries to parse this empty string as as json.
Lets fix this for now by not parsing this empty string, and just telling the user that the lookup failed. 
Currently the crisis-room crashes, and the user has no way to navigate somewhere else as they cannot see any navigation.

The better fix, making sure the octopoes doesn't crash, needs a new ticket.

**Comment by praseodym** [comment]
How many findings is too many, i.e. when was Rocky/Octopoes observed to crash?

**Comment by praseodym** [comment]
#647 will prevent Rocky from crashing. #653 was created to resolve the slow Crisis Room page when there are no crashes involved.
