### ISSUE TITLE
Extra info in Bits

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#614]

**Comment by Lisser** [comment]
For context: Bits are run on OOI's regardless whether the required boefje / normalizer has run. Therefor, the Bit makes an assumption on unknown data, resulting in false positives. 

For Octopoes v2, the proposal is to fix this by restricting execution of Bits by matching scan-levels of the BitDefinition and the OOI. When an OOI gets the required scan-level, the expected data will flow in at some later point time, so that the Bit has sufficient data before drawing a conclusion.

For Octopoes v3, Octopoes should in general be more aware of when sufficient knowledge is acquired before making inferencing.

**Comment by noamblitz** [comment]
Is this fixed when bits only run on oois with clearence level?

**Comment by Lisser** [comment]
Yes, with https://github.com/minvws/nl-kat-coordination/pull/645/files

Fixing the robot tests now
