### ISSUE TITLE
refine docs from a user perspective

### ISSUE THREAD

**Issue by ring-ring-ring** [minvws/nl-kat-coordination#659]
Go through the docs thinking as a user; is everything in the right place? This should help to answer user requests ('the information in the docs is too much scattered')

- I want to understand OpenKAT and see if it might work for my situation? 
- I want to install OpenKAT
- I want to use OpenKAT, check out findings, create reports, verify information
- I want to debug OpenKAT
- I want to contribute to OpenKAT

**Comment by praseodym** [comment]
We should also make the documentation more discoverable for new users, I'd suggest:
- Cleaning up the README.rst file to include only a short description of OpenKAT and most importantly a link to the documentation, so that we directly point new users to the docs
- Setting the docs website as the repository website in the repo (it will then appear at the top right of the repo start page)

**Comment by ring-ring-ring** [comment]
I've made a proposal to move the contents of the readmes of all modules to the developer documentation: https://github.com/minvws/nl-kat-coordination/pull/828
