### ISSUE TITLE
Werkt niet met Safari

### ISSUE THREAD

**Issue by eric-nieuwland** [minvws/nl-kat-coordination#7]
### Describe the bug, issue or concern

Na installatie op een Mac werkt de user-interface in Safari alleen voor de eerste pagina('s).
Daarna volgt een CSRF-foutmelding.

### To Reproduce

1. Installeer volgens handleiding
2. Ga met browser naar localhost:8000
3. Volg de stappen zoals gepresenteerd in de browser

### Expected behavior

Je zou hopen dat het gewoon doorloopt.
Met Firefox is dat wel zo (hoewel de schermen er anders uitzien dan in de handleiding).

**Desktop (please complete the following information):**
 - OS: macOS 12.4 Monterey
 - Browser Safari 15.5

**Comment by Rieven** [comment]
For Safari set cookie secure variables to false in rocky/settings.py:

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

**Comment by underdarknl** [comment]
Dear @eric-nieuwland did you get things working, or would you require some assistance?

**Comment by underdarknl** [comment]
Dear @eric-nieuwland our new version generates a self-signed cert to avoid this issue. It does introduce a new issue, as you would now need to click trough the ssl warning of your browser.
We opted for this route because we think having encryption (even self signed) is better than having no encryption by default. The possible negative effect of teaching people to click away warnings seems like something we can trust our userbase (security minded people) wtith.
