### ISSUE TITLE
Unified approach to dependency management (`requirements.txt`)

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#735]
**Is your feature request related to a problem? Please describe.**
Currently, we have no standardized approach to dependency management in the various modules, aside from that we use `pip`'s `requirements.txt`.

**Describe the solution you'd like**
Some things worth considering:

- Using Poetry and a lock file (implemented in Keiko and Octopoes by @Lisser)
    - Has some nice features for managing `venv`s as well   
- A single top-level `requirements.txt` instead of per module
    - How would this impact the ability to package and run the modules in this repository individually?
- How to distinguish between production/development/CI dependencies (e.g. linters)?
    - Currently, we use seperate requirements files
- How can we do this in such a way that we have minimal extra work for Debian packaging?
- Integration with dependabot is definitely nice to have

**Additional context**
https://github.com/minvws/nl-kat-coordination/pull/729

**Comment by praseodym** [comment]
I'd be in favour of one single list of dependencies so that we can share a single venv across all modules. This would also greatly speed up builds (e.g. we could base all Docker images off a single Python+venv base image).

I think this should also enable us to work with a single pyproject.toml for Poetry. Poetry also supports [dependency groups](https://python-poetry.org/docs/master/managing-dependencies/) so we can split out dev/ci/formatter/docs dependencies if we'd like.

**Comment by ammar92** [comment]
I would opt for poetry too and exporting of `requirements.txt` formats to be used for building the images.

> I'd be in favour of one single list of dependencies so that we can share a single venv across all modules. This would also greatly speed up builds (e.g. we could base all Docker images off a single Python+venv base image).

I'm not (yet) in favor of having a single virtual environment for the entire project, because we still consider them as isolated "microservices". And even if we don't see them as such, but as e.g. standalone packages, it would still be easier to have separate environments for both development and deployment. Although your suggestion would indeed improve build speeds.

**Comment by dekkers** [comment]
I'm working on moving our Debian packages to properly use Debian packages for the python dependencies. In that case it would be impossible to install the Debian packages if they have conflicting requirements, so I don't see the value of specifying for example the FastAPI version per service if they have to be the same.

**Comment by dekkers** [comment]
I've used pip-compile from [pip-tools](https://github.com/jazzband/pip-tools) in the past. It supports defining dependencies in pyproject.toml and also supports test/dev/docs dependencies with project.optional-dependencies. Pip-compile also supports generating hashes with `--generate-hashes`.  So as far as I can see we can do everything with pip-compile that we can do with poetry.

I think the major benefit of pip-compile compared to poetry is that pip-compile only outputs the requirement files. The requirement files are also easy to read and also shows the reverse dependencies of each package (see examples in the pip-tools readme). In constrast poetry has a gigantic and unreadable poetry.lock file that we need to include in git if we want to use poetry.

**Comment by Darwinkel** [comment]
Status:

- [x] project root
- [x] keiko
- [x] octopoes
- [ ] boefjes
- [ ] bytes
- [ ] mula
- [ ] rocky

**Comment by Darwinkel** [comment]
Just realised that `boefjes` requirements are actually somewhat complicated. They are partially generated from the requirements of the boefje modules, which do not include hashing, and in some cases, are not even pinned. We should probably fix this.

![image](https://github.com/minvws/nl-kat-coordination/assets/9536436/cd4bf249-bd08-4e6c-8df2-155fae1a31db)

**Comment by praseodym** [comment]
We'll be changing this when we move to new Normalisers and Boefjes runners. For now, maybe integrate everything in the Poetry configuration with clear comments of what dependencies are needed for each plugin?

**Comment by Darwinkel** [comment]
> We'll be changing this when we move to new Normalisers and Boefjes runners. For now, maybe integrate everything in the Poetry configuration with clear comments of what dependencies are needed for each plugin?

I've checked and modified the pipeline a bit in the linked PR. It's fine for now imho and does its job. We'll refactor this when we get to containerization.
