### ISSUE TITLE
Please make faster / add indices

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#897]
**Describe the bug**
At request of @underdarknl and @dekkers 

```sql
ula=# EXPLAIN (ANALYZE, BUFFERS)
mula-# SELECT tasks.id AS tasks_id, tasks.scheduler_id AS tasks_scheduler_id, tasks.type AS tasks_type, tasks.p_item AS tasks_p_item, tasks.status AS tasks_status, tasks.created_at AS tasks_created_at, tasks.modified_at AS tasks_modified_at FROM tasks WHERE CAST((tasks.p_item ->> 'hash') AS VARCHAR) = '735acb61a40xa3f673d1fb4b9dfb812e' ORDER BY tasks.created_at DESC LIMIT 1;
                                                                 QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=126515.60..126515.72 rows=1 width=1143) (actual time=24562.657..24562.737 rows=1 loops=1)
   Buffers: shared hit=13641 read=107551
   ->  Gather Merge  (cost=126515.60..126851.39 rows=2878 width=1143) (actual time=24556.789..24556.869 rows=1 loops=1)
         Workers Planned: 2
         Workers Launched: 0
         Buffers: shared hit=13641 read=107551
         ->  Sort  (cost=125515.58..125519.17 rows=1439 width=1143) (actual time=24556.474..24556.475 rows=1 loops=1)
               Sort Key: created_at DESC
               Sort Method: top-N heapsort  Memory: 28kB
               Buffers: shared hit=13641 read=107551
               ->  Parallel Seq Scan on tasks  (cost=0.00..125508.38 rows=1439 width=1143) (actual time=685.654..24556.346 rows=24 loops=1)
                     Filter: ((p_item ->> 'hash'::text) = '735acb61a40xa3f673d1fb4b9dfb812e'::text)
                     Rows Removed by Filter: 693111
                     Buffers: shared hit=13641 read=107551
 Planning Time: 0.084 ms
 JIT:
   Functions: 5
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 0.798 ms, Inlining 0.000 ms, Optimization 0.336 ms, Emission 5.288 ms, Total 6.422 ms
 Execution Time: 24563.631 ms
(20 rows)
```

**To Reproduce**
1. Use KAT
2. Check PostgreSQL

**Expected behavior**
Faster execution time

**OpenKAT version**
1.8.2rc2

**Comment by underdarknl** [comment]
https://www.postgresql.org/docs/7.3/indexes-functional.html
We should introduce an index on the p_item column, which contains the hashed data.

**Comment by jpbruinsslot** [comment]
If I'm not mistaken the functional index is applied to a column, and thus can't be used in this instance. Since the hash that we generate needs to be specific for that type of task for that organization. For a `BoefjeTask` we generate the hash from the fields `input_ooi`, `boefje_id`, and `organization_id`. A `p_item` that contains a `BoefjeTask` has variable fields such as `created_at`, `modified_at`, and `priority`. Hashing over the entire column will then result in different hashes for the same type of tasks. It will then become more difficult to match those types of tasks for checking if the same task is on the queue, if their grace period has passed, and fetch prior tasks for ranking.

However, by using the postgres JSONB column we can create an index on a specific field. And since a `p_item` contains the hash field containing `BoefjeTask` we can use that. ([pr](https://github.com/minvws/nl-kat-coordination/pull/912/files#diff-5b43166756df800f663c3d1307bff2683e76a44e5eeb1b1023f0e2911983d888L75-L76)
