### ISSUE TITLE
Docker is dropping support for compose V1

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#905]
We should investigate the consequences of this and perhaps update the Makefiles:

![Image](https://user-images.githubusercontent.com/46660228/235883301-2aa75bd7-2996-456b-bf3e-44ab3019d4e8.png)

**Comment by praseodym** [comment]
Even the upcoming Debian 12 Bookworm doesn't seem to have Docker Compose v2 available at all, so we could recommend installing the [upstream Docker Engine packages](https://docs.docker.com/engine/install/debian/) instead.

Because v1 and v2 are mostly compatible, if we keep using the `docker-compose` command (instead of `docker compose`) we should be able to support both for the time being.

**Comment by Donnype** [comment]
This was solved in https://github.com/minvws/nl-kat-coordination/pull/2341
