### ISSUE TITLE
Some users may not be able to finish the onboarding due to an insufficient clearance level on their account

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#908]
When onboarding a new redteam member, a clearance level of L2 is at least needed to scan a URL object during the onboarding. An extension of https://github.com/minvws/nl-kat-coordination/issues/880

**Issues:**
1. There is no place where a redteamer can acknowledge for L2 clearance during onboarding.
2. Admins can give clearance to redteamers, so admins must also at least give redteamers a clearance of L2, otherwise onboarding a redteamer cannot continue or at least proceed further than scanning.

**Solutions and discussions:**
- Admins cannot create redteamers that has not at least a clearance of L2 (accepted clearance level)
- Admins get a warning that a clearance of L2 is at least needed for a proper redteam onboarding.

What will happen if admin did not give clearance for L2? 
- What is the user flow when onboading? Do we proceed till scanning or at the beginning we say that there is no clearance.

**Feature needed:**
- A screen or split wizard flow to include clearance level acknowledgement. @HeleenSG and @NoemiOverdijk is going to look into this. Show clearance level admins gave to redteamer (accepted clearance level)

**Comment by HeleenSG** [comment]
The first part @Rieven  mentioned will be picked up in a different ticket.
"There is no place where a redteamer can acknowledge for L2 clearance during onboarding." By adding it to the onboarding flow. 

**The part we would like to discuss here is:** 
The current onboarding flow asks the user to assign clearance level 2 to an object. But what if the user doesn't have permission to do so? This results in the user being unable to finish onboarding.

**Possible solutions that we've discussed so far are:**
- When creating a red teamer, an admin must give a clearance level of at least level 2. 
- Change the example in the onboarding so a lower clearance level is needed. (0, cause level 1 would just move the problem without actually solving it) 
- Grant the user temporary clearance for the duration of the onboarding (This will be confusing to users so wouldn't recommend from an ux perspective. And it might have legal/responsibility issues since the user chooses the url to scan and might not have permission to do so.) 
- Admins get a warning that a clearance of L2 is at least needed for a proper redteam onboarding.

Please add suggestions, thoughts etc.
