### ISSUE TITLE
Provide the inner exception of boefjes in the raw output

### ISSUE THREAD

**Issue by ammar92** [minvws/nl-kat-coordination#919]
**Is your feature request related to a problem? Please describe.**
When a plugin, specifically a boefje, fails, the raw output will display "Boefje failed" which is not very helpful. It would be nicer if a boefje throws an exception to have that exception message (and/ or stack trace) in the raw output instead. This also helps in detecting errors in boefjes and detecting breaking changes due to e.g. API or backend updates.

**Describe the solution you'd like**
On boefje execution failure provide:
- inner exception message
- traceback

**Describe alternatives you've considered**
An alternative would be to provide the logs in the raw output. But I think a nicer feature would be to write these to a log file on each run instead of raw output.

**Comment by Darwinkel** [comment]
I think this is a necessary improvement. Especially with boefjes which only fail in some specific instances "Boefje failed" is not very helpful.

**Comment by underdarknl** [comment]
Since our target-platform for running boefjes is something cleanly containerized/sandboxed, we have only two output channels available. The regular output, eg, a set of mimetyped rawfiles, and an error-channel. This maps to std-out and std-err.
The runner should see what the exit state of the job was, and add mime-types to both sets accordingly.
any file in the std-out set would be labeled with the boefjes name etc, and the same goes for the single output stream in std-err. Which should be given a mime-type denoting its an error.

Whatever is in that error-raw file is of no concern to the boefje itself, and should also not be python centered, as boefjes might be any other language. Python (and many other languages) will simply dump their stackstrace to std-err, which is exactly what we'd expect from a boefje crashing.

**Comment by Donnype** [comment]
Something like this? https://github.com/minvws/nl-kat-coordination/pull/936
